export const FETCH_MESSAGES_SUCCESS = 'hinto-widget/FETCH_MESSAGES_SUCCESS'
export const INTERVAL_TICK = 'hinto-widget/INTERVAL_TICK'
export const CLEAR_STATE = 'hinto-widget/CLEAR_STATE'
export const MESSAGE_UNMOUNT = 'hinto-widget/MESSAGE_UNMOUNT'
export const RECEIVE_USER_SETTINGS = 'hinto-widget/RECEIVE_USER_SETTINGS'
export const USER_CLOSED_MESSAGE = 'hinto-widget/USER_CLOSED_MESSAGE'
